### ISSUE TITLE
crier failing to report kunit-test-presubmit

### ISSUE THREAD

**Issue by fejta** [GoogleCloudPlatform/oss-test-infra#103]
```
{
 insertId: "1io8wcxf6ejq1m"  
 jsonPayload: {
  component: "crier"   
  error: "error setting status: status code 404 not one of [201], body: {"message":"Not Found","documentation_url":"https://developer.github.com/v3/repos/statuses/#create-a-status"}"   
  file: "prow/crier/controller.go:279"   
  func: "k8s.io/test-infra/prow/crier.(*Controller).processNextItem"   
  jobName: "b3623ad8-c82f-11e9-b096-0a580a2c044d"   
  jobStatus: {
   build_id: "1166055611327057920"    
   completionTime: "2019-08-26T18:43:06Z"    
   description: "Job succeeded."    
   pod_name: "b3623ad8-c82f-11e9-b096-0a580a2c044d"    
   prev_report_states: {…}    
   startTime: "2019-08-26T18:31:21Z"    
   state: "success"    
   url: "https://prow.gflocks.com/view/gcs/oss-prow/pr-logs/pull/kunit-review.googlesource.com_linux/2370/kunit-test-presubmit/1166055611327057920"    
  }
  level: "error"   
  msg: "failed to report job"   
  prowjob: "default/b3623ad8-c82f-11e9-b096-0a580a2c044d"   
 }
 labels: {…}  
 logName: "projects/oss-prow/logs/crier"  
 receiveTimestamp: "2019-09-28T00:07:44.841801148Z"  
 resource: {…}  
 severity: "ERROR"  
 timestamp: "2019-09-28T00:07:41Z"  
}
```

That's an odd url

/kind oncall-hotlist

**Comment by krzyzacy** [comment]
oh I know this one...

**Comment by krzyzacy** [comment]
I cannot find the original issue though...

The problem is github reporter was trying to report a gerrit job as there's no way to tell if a prowjob is from github or gerrit. (and this prow instance talks to both github and gerrit)

**Comment by fejta** [comment]
That is a bug though, right?

**Comment by BenTheElder** [comment]
what's the status on this?

**Comment by fejta** [comment]
Still happening
```yaml
{
 insertId: "ftk6hug4urda6x"  
 jsonPayload: {
  component: "crier"   
  error: "error setting status: status code 404 not one of [201], body: {"message":"Not Found","documentation_url":"https://developer.github.com/v3/repos/statuses/#create-a-status"}"   
  file: "prow/crier/controller.go:279"   
  func: "k8s.io/test-infra/prow/crier.(*Controller).processNextItem"   
  jobName: "e7b6bb67-d005-11e9-84a3-c68839286cc4"   
  jobStatus: {
   build_id: "1169669630457810944"    
   completionTime: "2019-09-05T18:00:55Z"    
   description: "Job succeeded."    
   pod_name: "e7b6bb67-d005-11e9-84a3-c68839286cc4"    
   prev_report_states: {
    gerrit-reporter: "success"     
   }
   startTime: "2019-09-05T17:52:19Z"    
   state: "success"    
   url: "https://prow.gflocks.com/view/gcs/oss-prow/pr-logs/pull/kunit-review.googlesource.com_linux/2449/kunit-test-presubmit/1169669630457810944"    
  }
  level: "error"   
  msg: "failed to report job"   
  prowjob: "default/e7b6bb67-d005-11e9-84a3-c68839286cc4"   
 }
 labels: {…}  
 logName: "projects/oss-prow/logs/crier"  
 receiveTimestamp: "2019-10-11T20:33:26.109823851Z"  
 resource: {
  labels: {
   cluster_name: "prow"    
   container_name: "crier"    
   instance_id: "6234379657828418500"    
   namespace_id: "default"    
   pod_id: "crier-7bf477fddd-jfkgn"    
   project_id: "oss-prow"    
   zone: "us-west1-a"    
  }
  type: "container"   
 }
 severity: "ERROR"  
 timestamp: "2019-10-11T20:33:20Z"  
}
```
