### ISSUE TITLE
approve enabled in repos without OWNERS files

### ISSUE THREAD

**Issue by fejta** [GoogleCloudPlatform/oss-test-infra#127]
Repos with this problem:
- [ ] guest-agent - https://github.com/GoogleCloudPlatform/guest-agent/issues/3
- [ ] compute-images-packages - https://github.com/GoogleCloudPlatform/compute-image-packages/issues/859

```yaml
{
 insertId: "3206wog42gdrsb"  
 jsonPayload: {
  author: "adjackura"   
  component: "hook"   
  event-GUID: "a5d1a300-ebb8-11e9-9868-406a0c1c7f7f"   
  event-type: "issue_comment"   
  file: "prow/plugins/approve/approvers/owners.go:164"   
  func: "k8s.io/test-infra/prow/plugins/approve/approvers.Owners.GetSuggestedApprovers"   
  level: "warning"   
  msg: "Couldn't find/suggest approvers for each files. Unapproved: [""]"   
  org: "GoogleCloudPlatform"   
  plugin: "approve"   
  pr: 2   
  repo: "guest-agent"   
  url: "https://github.com/GoogleCloudPlatform/guest-agent/pull/2#issuecomment-540843760"   
 }
 labels: {…}  
 logName: "projects/oss-prow/logs/hook"  
 receiveTimestamp: "2019-10-10T23:49:58.731720740Z"  
 resource: {…}  
 severity: "ERROR"  
 timestamp: "2019-10-10T23:49:53Z"  
}
```
