### ISSUE TITLE
Migrate to default_decoration_configs

### ISSUE THREAD

**Issue by fejta** [GoogleCloudPlatform/oss-test-infra#135]
```yaml
{
 insertId: "1l5t5s7fulrh9c"  
 jsonPayload: {
  component: "hook"   
  file: "prow/config/config.go:986"   
  func: "k8s.io/test-infra/prow/config.(*Config).finalizeJobConfig"   
  level: "warning"   
  msg: "default_decoration_config will be deprecated on April 2020, and it will be replaced with default_decoration_configs['*']."   
 }
 labels: {…}  
 logName: "projects/oss-prow/logs/hook"  
 receiveTimestamp: "2019-10-15T18:10:06.542949020Z"  
 resource: {…}  
 severity: "ERROR"  
 timestamp: "2019-10-15T18:10:05Z"  
}
```

/assign
/kind oncall-hotlist
