### ISSUE TITLE
plank.allow_cancellations is deprecated

### ISSUE THREAD

**Issue by fejta** [GoogleCloudPlatform/oss-test-infra#178]
```yaml

{
 insertId: "wqxj9cg6l82b79"  
 jsonPayload: {
  component: "tide"   
  file: "prow/config/config.go:1258"   
  func: "k8s.io/test-infra/prow/config.parseProwConfig"   
  level: "warning"   
  msg: "The `plank.allow_cancellations` setting is deprecated. It will be removed and set to always true in March 2020"   
 }
 labels: {…}  
 logName: "projects/oss-prow/logs/tide"  
 receiveTimestamp: "2019-12-04T22:56:59.879872048Z"  
 resource: {…}  
 severity: "ERROR"  
 timestamp: "2019-12-04T22:56:55Z"  
}
```

/kind oncall-hotlist
