### ISSUE TITLE
Use crier to report to github

### ISSUE THREAD

**Issue by fejta** [GoogleCloudPlatform/oss-test-infra#181]
I'm seeing
```yaml
{
 insertId: "1fm21jlg7mcygnw"  
 jsonPayload: {
  component: "plank"   
  file: "prow/flagutil/github.go:107"   
  func: "k8s.io/test-infra/prow/flagutil.(*GitHubOptions).GitHubClientWithLogFields"   
  level: "warning"   
  msg: "empty -github-token-path, will use anonymous github client"   
 }
 labels: {…}  
 logName: "projects/oss-prow/logs/plank"  
 receiveTimestamp: "2019-12-05T22:09:39.247181734Z"  
 resource: {…}  
 severity: "ERROR"  
 timestamp: "2019-12-05T22:08:53Z"  
}
```
messages

See https://github.com/istio/test-infra/issues/1976 for something similar

/kind oncall-hotlist
