### ISSUE TITLE
Presubmit tests failing 

### ISSUE THREAD

**Issue by nathanperkins** [GoogleCloudPlatform/oss-test-infra#2366]
#2364 is failing presubmits because the build client is missing for the default build cluster:

```
status:
  completionTime: "2024-09-03T23:12:52Z"
  description: 'Terminal error: nonretryable error: no build client found for cluster
    "default".'
  prev_report_states:
    github-reporter: error
  startTime: "2024-09-03T23:12:52Z"
  state: error
```

It is missing because it could not contact the build cluster:

```
[failed to construct manager for cluster default: Get "https://35.233.240.207/api?timeout=32s": dial tcp 35.233.240.207:443: i/o timeout, failed to construct manager for cluster build: Get "https://35.233.240.207/api?timeout=32s": dial tcp 35.233.240.207:443: i/o timeout]
```

This is happening because the build cluster changed IPs.

A fix is in progress to update the build cluster kubeconfig: #2365
