### ISSUE TITLE
No build client found for cluster "build-kubeflow"

### ISSUE THREAD

**Issue by andreyvelich** [GoogleCloudPlatform/oss-test-infra#2430]
We are getting this error in our pre-commit tests for the `kubeflow/internal-acls` repo: https://github.com/kubeflow/internal-acls/pull/743

```
status:
  completionTime: "2025-02-05T18:36:11Z"
  description: 'Terminal error: nonretryable error: no build client found for cluster
    "build-kubeflow".'
  prev_report_states:
    github-reporter: error
  startTime: "2025-02-05T18:36:04Z"
  state: error
```

Any thoughts how we can fix it @nathanperkins @zijianjoy @james-jwu @airbornepony @chases2 @cjwagner @michelle192837 @nathanperkins ?

cc @franciscojavierarceo @terrytangyuan @juliusvonkohout @johnugeorge

**Comment by cjwagner** [comment]
The Prow service components can not connect to the `build-kubeflow` cluster for some reason:
```
failed to construct manager for cluster build-kubeflow: Get "https://34.73.99.137/api?timeout=32s": dial tcp 34.73.99.137:443: i/o timeout
```

We'll probably need to re-register the build-kubeflow cluster here: https://github.com/GoogleCloudPlatform/oss-test-infra/blob/master/prow/oss/cluster/kubeconfigs/kubeconfigs.yaml and remove the old credentials.

@andreyvelich Do you know where this cluster lives (GCP project and cluster name)? Do you have access to generate a kubeconfig using `gcloud container clusters get-credentials` so that we can add the relevant contents to the above file?

**Comment by andreyvelich** [comment]
I think, @zijianjoy @james-jwu should know about it.
I only have access to the `kubeflow-admin` project, where we run our GitHub sync.

**Comment by andreyvelich** [comment]
Looking at this, the GCP project name might be `kubeflow-ci`
https://github.com/GoogleCloudPlatform/oss-test-infra/blob/master/prow/oss/config.yaml#L261

**Comment by andreyvelich** [comment]
Hi Folks, please can someone help us with this issue since it blocks the sync for the Kubeflow ACLs?
Do we have anyone who has access to the `kubeflow-ci` GCP project ?

cc @nathanperkins @zijianjoy @james-jwu @airbornepony @chases2 @cjwagner @michelle192837 @thesuperzapper @jbottum @juliusvonkohout @rimolive

**Comment by tenzen-y** [comment]
I do not have any permissions for any GCP projects.

**Comment by michelle192837** [comment]
I don't have permissions on that project, nor can I find breadcrumbs for who might.

**Comment by cjwagner** [comment]
I cannot view the `kubeflow-ci` GCP project either.

**Comment by andreyvelich** [comment]
@cjwagner I was able to access `kf-ci-v1` cluster on `kubeflow-ci` GCP project.
Here is the cluster info:
```yaml

- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVMRENDQXBTZ0F3SUJBZ0lRTkJKV3BMaEtrSXJ3ZHBuSEZzRlpqakFOQmdrcWhraUc5dzBCQVFzRkFEQXYKTVMwd0t3WURWUVFERXlSaE56QTVNelUyWlMwNVptWmhMVFF3WkRNdFlqZGxaaTAyWVRKaE1tRTNaR0ptTWpNdwpJQmNOTWpVd01USTNNakl5T1RFM1doZ1BNakExTlRBeE1qQXlNekk1TVRkYU1DOHhMVEFyQmdOVkJBTVRKR0UzCk1Ea3pOVFpsTFRsbVptRXROREJrTXkxaU4yVm1MVFpoTW1FeVlUZGtZbVl5TXpDQ0FhSXdEUVlKS29aSWh2Y04KQVFFQkJRQURnZ0dQQURDQ0FZb0NnZ0dCQUxmcGlFVEtIejVEUXFjSFFKWDVSZGZWcWxwUW9YUWZsRUZJRGs3QwpHTFYwY05PMnpDSmxlZzl4SmpFOVA2L1ZLMjdLcDF5ZGZVdEZPc3o4cU9iMGhxWllXSU1hUkxzRndjdGE3a0ovCnFYeGxPWnZMVlh2YU81WmgxMTkzaGJlNHgvODJBMlJCVmhtbFY4RFlWd2ppbGwwMkx0Z3ZnK1JpMVlicDF1dDkKcG85Tm9MNEtOR2dZTS9KcVBwbHNDV0tSTUs3S0J2alFqZUpWY2pLSW9pUkVaNHBmL1dwUEhNQVliMW5HZGkwQQpxczNiQ0YwUVU1Y3JNVENyaElxa09hLzNaQVNoL1dFcXRhZTJjL2ZGbnJPVXpBYjNicHNqWjVvTWtjYWV5SkJ5ClVBNERlTmh6WDBoUXdVQ3RualNETXhUN2FvZTNDZkRIUHdORVE4YnhBb3ZQTW5rQVdLdytZQ09iY3FFdGZGVWcKUUFVWUE1NmVrYlByR2VEWmExNDZ0anhXdzFnQ0JDL1BVUWRaZkhGZ3lwdGMzamhvL0RpNVZjWHBnVkVKSUF4bQp6MS90MW52N2VuZ2Jtd0pTUWZsMlM3WnN1QXYxZlErd1g2R255K3EyeDVrV25CQm5KWVN4TFdWUDJBbGwyZ3hnClppeDQ3Z2RZa1Y4cW14QTN6c05xbVV0VmNRSURBUUFCbzBJd1FEQU9CZ05WSFE4QkFmOEVCQU1DQWdRd0R3WUQKVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVVMcE1nZTVTODlIVC9BZWkzUWxZNENueTV6Nnd3RFFZSgpLb1pJaHZjTkFRRUxCUUFEZ2dHQkFKOEs4TFlRVmd2SUtBRHVySlRaTFJmc20xbEFKUUZRSXM3Z3hRZ2ZuMmJ2Ck1qSlBBV2pwZ1FkaFpnU3VFM3hkZzZjZHFpYjE5WlRnZWo5MzQ2NkxoNVRIR2kvT0VMZlppMS9FWU1xYW5zZU4KSVhqL3BreFBrTDBKdDFxNi9DZTNZQjVGVXJ5UFV4RXg0UC9yQ2lpMzliUkNZWEcwZlVwbUp3amVCS3dLWXFodwpaQzMyTEJsYWRtZGN4Y1FudXdWbFNNUnlpS01jVjVRdWMxQUwveVpZM2RTSHcxdndjWnJEMHhqaDVoS2t4bUpjClNodk1EekVIVHhEZEVsb2NVbGN1aXpCU0p1Z09xSjN1cERtemsrUVNWeXppV1phWE9jWm1ZM0p2K29JLzVBZ0cKTndzYVpwR3k2UTR1TkRaazE4UEpqaCtOamdvcXhRM3l0L0xqQmYvWU4xcVZWQ2RDRy9ZM3pOSThVcHFGczVmdApDRVlnOWhoL1l1QWlrMmc0YitsRWxVY1dXSnZOZ1owSUc1ZEhPZ2poMFVaUTY4UHI2VFJ3KzVxeUo5bGR5WFJRCkdxY3krOXdoTkt4cjR0bmRxWWFhMG5idlVZRmd6d0l3Tzh6N3V2MVY2T2pYcVVmVGlxUG94cXFERUlPbVFwNG4KZ1JWVVlGYTBOckhqUmJ2bUxrUGowQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://34.148.99.131
  name: gke_kubeflow-ci_us-east1-d_kf-ci-v1
```

Do you need anything else from me ?
