### ISSUE TITLE
Cannot list pods in kubeflow cluster

### ISSUE THREAD

**Issue by fejta** [GoogleCloudPlatform/oss-test-infra#252]
```yaml
{
 insertId: "1e8iuueg2rjyho6"  
 jsonPayload: {
  component: "plank"   
  error: "errors syncing: [error listing pods in cluster "kubeflow": Get https://35.196.213.148/api/v1/namespaces/test-pods/pods?labelSelector=created-by-prow%3Dtrue: dial tcp 35.196.213.148:443: connect: connection refused], errors reporting: []"   
  file: "prow/cmd/plank/main.go:149"   
  func: "main.main.func2"   
  level: "error"   
  msg: "Error syncing."   
 }
 labels: {…}  
 logName: "projects/oss-prow/logs/plank"  
 receiveTimestamp: "2020-01-21T19:02:28.929499401Z"  
 resource: {…}  
 severity: "ERROR"  
 timestamp: "2020-01-21T19:02:24Z"  
}
```

/kind oncall-hotlist
