### ISSUE TITLE
Tide is failing to set status in GoogleCloudPlatform/compute-image-tools

### ISSUE THREAD

**Issue by cjwagner** [GoogleCloudPlatform/oss-test-infra#308]
Example:
```yaml
{
  component: "tide"   
  controller: "status-update"   
  error: "status code 404 not one of [201], body: {"message":"Not Found","documentation_url":"https://developer.github.com/v3/repos/statuses/#create-a-status"}"   
  file: "prow/tide/status.go:393"   
  func: "k8s.io/test-infra/prow/tide.(*statusController).setStatuses.func1"   
  level: "error"   
  msg: "Failed to set status context from "PENDING" to "pending"."   
  org: "GoogleCloudPlatform"   
  pr: 1150   
  repo: "compute-image-tools"   
  sha: "1b3f5263ce6c6b6984dbc5539f157c837dabeae3"   
}
```

Since this is only happening on the compute-image-tools repo I suspect that the repo setting may have been accidentally changed to cause this. Perhaps the bot's permissions were demoted or removed?
cc @fejta @hopkiw
