### ISSUE TITLE
Gerrit adapter fails to query changes for project `linux`.

### ISSUE THREAD

**Issue by cjwagner** [GoogleCloudPlatform/oss-test-infra#309]
Example:
```yaml
{
  component: "gerrit"   
  error: "failed to query gerrit changes: API call to https://kunit-review.googlesource.com/a/changes/?n=5&o=CURRENT_REVISION&o=CURRENT_COMMIT&o=CURRENT_FILES&o=MESSAGES&q=project:linux failed: 403 Forbidden"   
  file: "prow/gerrit/client/client.go:276"   
  func: "k8s.io/test-infra/prow/gerrit/client.(*gerritInstanceHandler).queryAllChanges"   
  level: "error"   
  msg: "fail to query changes for project linux"   
}
```
Interestingly, these errors happen every minute, but only between the 42nd and 49th minutes of each hour.
Outside of this window queries appear to succeed. Example:
```yaml
{
  component: "gerrit"   
  file: "prow/gerrit/client/client.go:315"   
  func: "k8s.io/test-infra/prow/gerrit/client.(*gerritInstanceHandler).queryChangesForProject"   
  level: "info"   
  msg: "Find 5 changes from query [project:linux]"   
}
```
/kind bug
