### ISSUE TITLE
gerrit auth issue

### ISSUE THREAD

**Issue by fejta** [GoogleCloudPlatform/oss-test-infra#373]
```yaml
jsonPayload: {
  component: "gerrit"   
  file: "prow/cmd/gerrit/main.go:75"   
  func: "main.(*options).Validate"   
  last-sync-fallback: "gs://oss-prow/last-gerrit-sync"   
  level: "warning"   
  msg: "--gcs-credentials-file unset, will try and access with a default service account"   
 }
```

/kind oncall-hotlist
/assign

**Comment by fejta** [comment]
also

```yaml
jsonPayload: {
  component: "crier"   
  file: "prow/flagutil/github.go:70"   
  func: "k8s.io/test-infra/prow/flagutil.(*GitHubOptions).Validate"   
  level: "warning"   
  msg: "missing required flag: please set to --github-token-path=/etc/github/oauth before June 2020"   
 }
```

  
  msg: "--gcs-workers is deprecated and will be removed in August 2020. Use --blob-storage-workers instead." 

msg: "--kubernetes-gcs-workers is deprecated and will be removed in August 2020. Use --kubernetes-blob-storage-workers instead."   
 }
