### ISSUE TITLE
Onboard secrets-store-csi-driver-provider-gcp

### ISSUE THREAD

**Issue by colinman** [GoogleCloudPlatform/oss-test-infra#474]
We would like to onboard https://github.com/GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp to oss-test-infra to execute end-to-end tests for the GCP Secret Manager Secrets Store CSI Driver Provider.

As discussed offline, there is some setup work required to configure the Github webhooks.

**Comment by cjwagner** [comment]
Once [this PR](https://github.com/GoogleCloudPlatform/oss-test-infra/pull/475) merges and [`google-oss-robot`](https://github.com/google-oss-robot) has been granted admin access to your repo then it is safe to add an entry to the `managed_webhooks.org_repo_config` section of [`config.yaml`](https://github.com/GoogleCloudPlatform/oss-test-infra/blob/master/prow/oss/config.yaml). In particular: 
```yaml
managed_webhooks:
    respect_legacy_global_token: true
    org_repo_config:
        # Add this VV
        GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp:
            token_created_after: 2020-08-18T00:10:00Z
```
