### ISSUE TITLE
Tide is misconfigured to run on archived repos in the Knative org.

### ISSUE THREAD

**Issue by cjwagner** [GoogleCloudPlatform/oss-test-infra#482]
Example error:
```yaml
{
  branch: "master"   
  component: "tide"   
  controller: "status-update"   
  error: "status code 403 not one of [201], body: {"message":"Repository was archived so is read-only.","documentation_url":"https://docs.github.com/rest/reference/repos#create-a-commit-status"}"   
  file: "prow/tide/status.go:399"   
  func: "k8s.io/test-infra/prow/tide.(*statusController).setStatuses.func1"   
  level: "error"   
  msg: "Failed to set status context from "pending" to "pending" and description from "Not mergeable. Needs approved, lgtm labels." to "Not mergeable. Needs approved, cla: yes, lgtm labels.""   
  org: "knative"   
  pr: 99   
  repo: "build-templates"   
  sha: "fe8caddd82b8ba350b19b9b8c5c6539d6c380c0c"   
}
```

Please identify the archived repos in the orgs covered by the Tide query and omit them with `excludedRepos`. e.g. https://github.com/kubernetes/test-infra/blob/11c2b2aeff809375b539f532e09504b8bc171a31/config/prow/config.yaml#L449-L485

/kind bug
/cc @chaodaiG @chizhg
