### ISSUE TITLE
knative-prow's Deck instance is not properly configured to use TestGrid.

### ISSUE THREAD

**Issue by cjwagner** [GoogleCloudPlatform/oss-test-infra#539]
```yaml
{
  component: "deck"   
  error: "googleapi: got HTTP response code 403 with body: <?xml version='1.0' encoding='UTF-8'?><Error><Code>AccessDenied</Code><Message>Access denied.</Message><Details>Primary: /namespaces/knative-tests.svc.id.goog with additional claims does not have storage.objects.get access to the Google Cloud Storage object.</Details></Error>"   
  file: "prow/spyglass/testgrid.go:50"   
  func: "k8s.io/test-infra/prow/spyglass.(*TestGrid).Start.func1"   
  level: "error"   
  msg: "Couldn't update TestGrid config."   
  path: "gs://knative-testgrid/config"   
}
```

It looks like this has probably been an issue since this was added in June of 2019? https://github.com/knative/test-infra/pull/991
/assign @chizhg 
/kind bug
