### ISSUE TITLE
Add --github-token-path to cherrypicker

### ISSUE THREAD

**Issue by fejta** [GoogleCloudPlatform/oss-test-infra#719]
```yaml
jsonPayload: {
file: "prow/flagutil/github.go:88"
component: "cherrypicker"
msg: "missing required flag: please set to --github-token-path=/etc/github/oauth before June 2020"
level: "warning"
func: "k8s.io/test-infra/prow/flagutil.(*GitHubOptions).Validate"
}
```

/kind oncall-hotlist
/assign
