### ISSUE TITLE
OSS Prow's Deck cannot update TestGrid config.

### ISSUE THREAD

**Issue by cjwagner** [GoogleCloudPlatform/oss-test-infra#810]
These errors started at 2021-04-23 01:08:50.000 PDT
```yaml
{
  component: "deck"   
  error: "Get "https://storage.googleapis.com/k8s-testgrid/config": metadata: GCE metadata "instance/service-accounts/default/token?scopes=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdevstorage.full_control" not defined"   
  file: "prow/spyglass/testgrid.go:50"   
  func: "k8s.io/test-infra/prow/spyglass.(*TestGrid).Start.func1"   
  level: "error"   
  msg: "Couldn't update TestGrid config."   
  path: "gs://k8s-testgrid/config"   
}
```
cc @michelle192837 @chaodaiG
