### ISSUE TITLE
Error on the external secret during ci-knative-eventing-s390x-e2e-tests

### ISSUE THREAD

**Issue by BbolroC** [GoogleCloudPlatform/oss-test-infra#866]
Got the following error after merging #843:

https://storage.googleapis.com/knative-prow/logs/ci-knative-eventing-s390x-e2e-tests/1395650582487764992/build-log.txt

It seems like there is a problem of loading the secret `s390x-cluster1`.

@chizhg Could you please go over this and suggest how to fix the problem?

Thank you.

**Comment by BbolroC** [comment]
To ease the investigation, the secrets in the secret manager follow the IAM policies below:

```
~ » gcloud secrets get-iam-policy kubeconfig
bindings:
- members:
  - serviceAccount:kubernetes-external-secrets-sa@knative-tests.iam.gserviceaccount.com
  role: roles/secretmanager.secretAccessor
- members:
  - serviceAccount:kubernetes-external-secrets-sa@knative-tests.iam.gserviceaccount.com
  role: roles/secretmanager.viewer
etag: BwXCDDOsGsc=
version: 1
~ » gcloud secrets get-iam-policy ko-docker-repository
bindings:
- members:
  - serviceAccount:kubernetes-external-secrets-sa@knative-tests.iam.gserviceaccount.com
  role: roles/secretmanager.secretAccessor
- members:
  - serviceAccount:kubernetes-external-secrets-sa@knative-tests.iam.gserviceaccount.com
  role: roles/secretmanager.viewer
etag: BwXCDDqRIDA=
version: 1
~ » gcloud secrets get-iam-policy registry-certificate
bindings:
- members:
  - serviceAccount:kubernetes-external-secrets-sa@knative-tests.iam.gserviceaccount.com
  role: roles/secretmanager.secretAccessor
- members:
  - serviceAccount:kubernetes-external-secrets-sa@knative-tests.iam.gserviceaccount.com
  role: roles/secretmanager.viewer
etag: BwXCDDza9_4=
version: 1
```

**Comment by chaodaiG** [comment]
I just inspected the build cluster with `k -ntest-pods get secrets s390x-cluster1 -oyaml`, and the secret was reconciled by external secret:
```
metadata:
  creationTimestamp: "2021-05-20T23:59:52Z"
  name: s390x-cluster1
  namespace: test-pods
  ownerReferences:
  - apiVersion: kubernetes-client.io/v1
    controller: true
    kind: ExternalSecret
    name: s390x-cluster1
```
